### ISSUE TITLE
Eclipse Plugin :  cannot find Node.js

### ISSUE THREAD

**Issue by tdebroc** [cincheo/jsweet-examples#11]
I have node js in my path in my terminal but Eclipse can't find it:
`
cannot find Node.js: install first and make sure that the 'node' command is in your execution path  jsweet-examples     Unknown JSweet Problem
`

**Comment by renaudpawlak** [comment]
Make sure that:
1. even when you close the terminal and restart it, node and npm are still in your path
2. you restart Eclipse too so that the path is up-to-date for Eclipse
Keep me posted

**Comment by renaudpawlak** [comment]
This issue was moved to cincheo/jsweet#19
