### ISSUE TITLE
Could not find artifact org.jsweet:jsweet-maven-plugin:jar:1.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by tdebroc** [cincheo/jsweet-examples#12]
I have a maven Build Failure:
`
[ERROR] Plugin org.jsweet:jsweet-maven-plugin:1.0.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.jsweet:jsweet-maven-plugin:jar:1.0.0-SNAPSHOT
`

**Comment by renaudpawlak** [comment]
Was it when building the jsweet-quickstart project or when building the jsweet-examples? There was a problem in the pom.xml of the jsweet-quickstart project that would have led to this error. It is fixed now though.

**Comment by renaudpawlak** [comment]
This issue was moved to cincheo/jsweet#18
