### ISSUE TITLE
gradle jsweet task not working 

### ISSUE THREAD

**Issue by LiborKuchejda** [cincheo/jsweet-examples#20]
when running "gradlew jsweet" error occures:

Cannot run program "C:\Users<username>.jsweet-node_modules\tsc.cmd" (in directory "D:\src\js\test\jsweet\jsweet-examples.ts"): CreateProcess error=2, The system cannot find the file specified
Unknown tsc error
:jsweet FAILED

**Comment by lgrignon** [comment]
I can't reproduce this problem, even on Windows, cleaning ~/.jsweet-node_modules and launching `gradlew jsweet` in jsweet-examples from another drive.

Do you reproduce the problem using maven?

Thanks for reporting anyway.

**Comment by LiborKuchejda** [comment]
I tested that on other machine and it works ok, so probably no issue. Just problem on my laptop.
Thanks

**Comment by lgrignon** [comment]
Nice, if everything is ok for you, could you please close this issue?

Thanks

**Comment by renaudpawlak** [comment]
It does not look like a solved issue to me. Maybe the problem comes from that you are running JSweet in D: and your home directory is in C:? Just in case, does your username contain spaces on your laptop? On your other computer, do you have C: and D: units too?

**Comment by lgrignon** [comment]
As I said, I tried with another drive, I didn't notice any problem :/

**Comment by renaudpawlak** [comment]
Spaces in user name then?

**Comment by lgrignon** [comment]
That was my next question ;)

**Comment by lgrignon** [comment]
Or special characters?

**Comment by LiborKuchejda** [comment]
Finally no spaces , no spacial characters.  npm itself does not work correctly on home directory on that system. maybe ntfs links causes that problem, it is corporate imaged system so not so standard. Closing as this is not jsweet problem.  Thanks.
