### ISSUE TITLE
Update to the latest Sweet

### ISSUE THREAD

**Issue by maximumspatium** [cincheo/jsweet-examples#22]
The examples still rely on JSweet 1.2.0-SNAPSHOT despite the fact [JSweet 1.2.0](https://github.com/cincheo/jsweet/releases/tag/v1.2.0) has been released.
Please update your configuration files accordingly.

Thank you in advance!

**Comment by renaudpawlak** [comment]
Done. However, the jsweet-core API will not released for 1.2, so you should continue using snapshots for the APIs and candies.
