### ISSUE TITLE
Ant only build

### ISSUE THREAD

**Issue by reenigneEsrever92** [cincheo/jsweet-examples#24]
I found that often projects of mine don't require lots of the stuff that gradle or maven give you in a java environment.
Hence I would like to make/change the ant build files to make a lightweight build of any JSweet project using only ant and eliminating the need to call maven within this procedure.

**Comment by lgrignon** [comment]
Please take a look at: https://github.com/cincheo/jsweet-examples/blob/master/build.xml

It is one of the solution for using JSweet along with Ant.

Note that this example use the maven pom.xml to copy dependencies to a lib directory. You could either use maven to download your dependencies and create a new clean project copying the dependencies you need and only the build.xml or download the dependencies manually.

I hope you will figure it out.
